#!/bin/bash

set -e

log "Generating virtual user ..."
export user_name=testuser
export user_mailbox="${DOVECOT_VMAIL}/${user_name}"
export user_password=testpassword

log "Starting supervisord ..."
/usr/bin/supervisord --configuration=/etc/supervisor/supervisord.conf &
sleep 1
while ! grep 'regeneration completed$' /var/log/supervisor/dovecot-stdout*.log > /dev/null ; do
	log "Waiting for dovecot ..."
	sleep 1
done

log "Initializing test user ..."
dovecot-add-user "${user_name}" "${user_password}"

if [[ -n "${DOVECOT_USE_MAILDIR}" ]] ; then
	install --directory --group="vmail" --mode=0770 --owner="vmail" "${user_mailbox}"/{,cur,new,tmp}
else
	install --group="vmail" --mode=0660 --owner="vmail" /dev/null "${user_mailbox}"
fi

log "Testing IMAP ..."
dovecot-test-imap "${user_name}" "${user_password}" "${user_mailbox}"

log "--- Test Passed ---"
exit 0
